[package]
name = "parsed"
version = "0.1.5"
authors = ["sergey-melnychuk"]
edition = "2018"
description = "Parser combinators library."
license = "MIT"
repository = "https://github.com/sergey-melnychuk/parsed"
readme = "https://github.com/sergey-melnychuk/parsed"

[dependencies]

