name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --features "http" --verbose
    - name: Run tests
      run: cargo test --features "http" --verbose
    - name: Run benches
      run: cargo test --features "http" --verbose
